### ISSUE TITLE
Decode error for coin-futures market, while spot market is ok.

### ISSUE THREAD

**Issue by xiangnanyue** [cckn1ght/crypto-data#1]
$ ../crypto-data.exe get-klines --market coin-futures --interval 1d   --start-time "2023-08-28 11:00:00"   --end-time "2024-07-29 11:00:00" --all

Start time: 2023-08-28 11:00:00 UTC, End time: 2024-07-29 11:00:00 UTC, saving files to: \\?\C:\Users\yuexn\PycharmProjects\crypto-model\release\crypto_futures_daily
thread 'main' panicked at src\utils.rs:166:60:
Can not get klines for BTCUSD_PERP: reqwest::Error { kind: Decode, source: Error("invalid type: map, expected a sequence", line: 1, column: 0) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by joe-dddd** [comment]
For coin-futures: "The difference between startTime and endTime can only be up to 200 days"
https://binance-docs.github.io/apidocs/delivery/en/#kline-candlestick-data
